In [2]:
import pandas as pd

In [7]:
data_path = "data/green_tripdate_2025-01.parquet"

df = pd.read_parquet(data_path)

print(f"Shape of data = {df.shape}")

df.head(40)

Shape of data = (48326, 21)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-01-01 00:03:01,2025-01-01 00:17:12,N,1.0,75,235,1.0,5.93,24.70,...,0.5,6.80,0.00,NaN,1.0,34.00,1.0,1.0,0.00,0.0
1,2,2025-01-01 00:19:59,2025-01-01 00:25:52,N,1.0,166,75,1.0,1.32,8.60,...,0.5,0.00,0.00,NaN,1.0,11.10,2.0,1.0,0.00,0.0
2,2,2025-01-01 00:05:29,2025-01-01 00:07:21,N,5.0,171,73,1.0,0.41,25.55,...,0.0,0.00,0.00,NaN,1.0,26.55,2.0,2.0,0.00,0.0
3,2,2025-01-01 00:52:24,2025-01-01 01:07:52,N,1.0,74,223,1.0,4.12,21.20,...,0.5,6.13,6.94,NaN,1.0,36.77,1.0,1.0,0.00,0.0
4,2,2025-01-01 00:25:05,2025-01-01 01:01:10,N,1.0,66,158,1.0,4.71,33.80,...,0.5,7.81,0.00,NaN,1.0,46.86,1.0,1.0,2.75,0.0
5,2,2025-01-01 01:03:45,2025-01-01 01:42:09,N,1.0,260,260,1.0,4.26,31.00,...,0.5,0.00,0.00,NaN,1.0,33.50,2.0,1.0,0.00,0.0
6,2,2025-01-01 00:28:12,2025-01-01 00:37:53,N,1.0,7,202,1.0,2.00,11.40,...,0.5,22.00,0.00,NaN,1.0,35.90,1.0,1.0,0.00,0.0
7,2,2025-01-01 00:25:38,2025-01-01 00:36:47,N,1.0,166,244,1.0,2.09,13.50,...,0.5,0.00,0.00,NaN,1.0,16.00,2.0,1.0,0.00,0.0
8,2,2025-01-01 00:52:04,2025-01-01 00:58:36,N,1.0,166,151,1.0,0.95,7.90,...,0.5,2.08,0.00,NaN,1.0,12.48,1.0,1.0,0.00,0.0
9,2,2024-12-31 22:42:13,2024-12-31 22:42:31,N,3.0,74,74,1.0,0.06,23.00,...,0.0,0.00,0.00,NaN,1.0,25.00,2.0,1.0,0.00,0.0
10,2,2024-12-31 23:01:11,2024-12-31 23:04:29,N,1.0,75,236,1.0,0.66,5.80,...,0.5,2.76,0.00,NaN,1.0,13.81,1.0,1.0,2.75,0.0
11,2,2025-01-01 00:18:31,2025-01-01 00:18:46,N,5.0,92,92,1.0,0.00,35.00,...,0.0,2.00,0.00,NaN,1.0,38.00,1.0,2.0,0.00,0.0
12,1,2025-01-01 00:13:44,2025-01-01 00:27:42,N,1.0,42,159,1.0,0.00,18.50,...,1.5,0.00,0.00,NaN,1.0,20.00,1.0,1.0,0.00,0.0
13,1,2025-01-01 00:54:41,2025-01-01 01:03:43,N,1.0,41,168,0.0,1.70,11.40,...,1.5,0.00,0.00,NaN,1.0,13.90,2.0,1.0,0.00,0.0
14,2,2025-01-01 00:36:38,2025-01-01 00:47:19,N,1.0,75,262,1.0,1.93,12.10,...,0.5,1.10,0.00,NaN,1.0,18.45,1.0,1.0,2.75,0.0
15,2,2025-01-01 00:31:59,2025-01-01 00:32:02,N,5.0,66,66,0.0,0.03,76.00,...,0.0,15.40,0.00,NaN,1.0,92.40,1.0,2.0,0.00,0.0
16,2,2025-01-01 00:01:40,2025-01-01 00:18:21,N,1.0,74,262,1.0,2.91,17.70,...,0.5,4.59,0.00,NaN,1.0,27.54,1.0,1.0,2.75,0.0
17,2,2025-01-01 00:24:44,2025-01-01 00:33:57,N,1.0,236,263,1.0,1.62,11.40,...,0.5,3.33,0.00,NaN,1.0,19.98,1.0,1.0,2.75,0.0
18,2,2025-01-01 00:20:31,2025-01-01 00:20:34,N,5.0,197,197,1.0,0.00,13.00,...,0.0,1.00,0.00,NaN,1.0,15.00,1.0,2.0,0.00,0.0
19,2,2025-01-01 00:17:17,2025-01-01 00:25:29,N,1.0,42,168,1.0,1.66,10.70,...,0.5,0.00,0.00,NaN,1.0,13.20,2.0,1.0,0.00,0.0
20,2,2025-01-01 00:55:57,2025-01-01 01:02:31,N,1.0,74,41,1.0,0.93,7.20,...,0.5,0.00,0.00,NaN,1.0,9.70,2.0,1.0,0.00,0.0
21,2,2025-01-01 00:04:05,2025-01-01 00:15:49,N,1.0,243,116,1.0,3.22,17.00,...,0.5,0.00,0.00,NaN,1.0,19.50,2.0,1.0,0.00,0.0
22,2,2025-01-01 00:41:30,2025-01-01 01:00:25,N,1.0,243,18,1.0,3.77,21.90,...,0.5,0.00,0.00,NaN,1.0,24.40,2.0,1.0,0.00,0.0
23,2,2025-01-01 00:08:44,2025-01-01 00:21:10,N,1.0,95,135,1.0,1.98,13.50,...,0.5,4.00,0.00,NaN,1.0,20.00,1.0,1.0,0.00,0.0
24,2,2025-01-01 00:28:23,2025-01-01 01:08:25,N,1.0,166,224,2.0,6.97,41.50,...,0.5,5.80,0.00,NaN,1.0,52.55,1.0,1.0,2.75,0.0
25,2,2025-01-01 00:09:57,2025-01-01 00:18:05,N,1.0,260,83,1.0,1.08,9.30,...,0.5,1.00,0.00,NaN,1.0,12.80,1.0,1.0,0.00,0.0
26,2,2025-01-01 00:11:49,2025-01-01 00:15:31,N,1.0,223,223,5.0,0.75,5.80,...,0.5,2.49,0.00,NaN,1.0,10.79,1.0,1.0,0.00,0.0
27,2,2025-01-01 00:14:15,2025-01-01 00:21:51,N,1.0,41,236,1.0,2.07,10.70,...,0.5,0.00,0.00,NaN,1.0,15.95,1.0,1.0,2.75,0.0
28,2,2025-01-01 00:48:38,2025-01-01 01:33:50,N,5.0,33,220,2.0,17.07,87.00,...,0.0,18.15,0.00,NaN,1.0,108.90,1.0,2.0,2.75,0.0
29,2,2025-01-01 00:30:53,2025-01-01 00:35:28,N,1.0,41,24,6.0,0.78,7.20,...,0.5,1.94,0.00,NaN,1.0,11.64,1.0,1.0,0.00,0.0
30,2,2025-01-01 00:43:45,2025-01-01 01:00:59,N,1.0,41,163,5.0,3.66,19.80,...,0.5,4.00,0.00,NaN,1.0,29.05,1.0,1.0,2.75,0.0
31,2,2025-01-01 00:01:11,2025-01-01 00:12:52,N,1.0,95,130,1.0,3.90,18.40,...,0.5,0.00,0.00,NaN,1.0,20.90,2.0,1.0,0.00,0.0
32,2,2025-01-01 00:40:22,2025-01-01 00:47:47,N,1.0,82,173,1.0,0.90,8.60,...,0.5,0.00,0.00,NaN,1.0,11.10,2.0,1.0,0.00,0.0
33,2,2025-01-01 00:14:07,2025-01-01 00:29:29,N,1.0,166,142,1.0,4.13,21.20,...,0.5,4.76,0.00,NaN,1.0,31.21,1.0,1.0,2.75,0.0
34,2,2025-01-01 00:50:36,2025-01-01 00:56:18,N,1.0,95,95,1.0,0.12,6.50,...,0.5,1.80,0.00,NaN,1.0,10.80,1.0,1.0,0.00,0.0
35,2,2025-01-01 00:43:40,2025-01-01 00:43:48,N,1.0,39,39,2.0,0.02,3.00,...,0.5,0.00,0.00,NaN,1.0,5.50,2.0,1.0,0.00,0.0
36,2,2025-01-01 00:36:30,2025-01-01 00:42:16,N,1.0,82,56,1.0,1.07,6.00,...,0.5,0.00,0.00,NaN,0.3,7.30,2.0,1.0,0.00,0.0
37,2,2025-01-01 01:01:54,2025-01-01 01:02:03,N,5.0,129,129,3.0,0.01,25.00,...,0.0,5.06,0.00,NaN,0.3,30.36,1.0,2.0,0.00,0.0
38,2,2025-01-01 00:13:23,2025-01-01 00:45:16,N,1.0,255,107,1.0,4.23,29.60,...,0.5,6.97,0.00,NaN,1.0,41.82,1.0,1.0,2.75,0.0
39,2,2025-01-01 00:48:47,2025-01-01 00:52:15,N,1.0,52,33,1.0,0.64,5.80,...,0.5,1.66,0.00,NaN,1.0,9.96,1.0,1.0,0.00,0.0

In [4]:
df.describe()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
count,48326.000000,48326,48326,46490.000000,48326.000000,48326.000000,46490.000000,48326.000000,48326.000000,48326.000000,48326.000000,48326.000000,48326.000000,0.0,48326.000000,48326.000000,46490.000000,46483.000000,46490.00000,46490.000000
mean,1.870215,2025-01-17 04:19:01.965753,2025-01-17 04:38:59.277448,1.184771,94.094545,142.409014,1.278103,21.532410,16.762466,0.932324,0.602776,2.481859,0.177461,NaN,0.988346,22.634242,1.266423,1.038788,0.85306,0.053350
min,1.000000,2024-12-25 23:13:15,2024-12-25 23:13:17,1.000000,3.000000,1.000000,0.000000,0.000000,-113.000000,-5.000000,-0.500000,-0.900000,0.000000,NaN,-1.000000,-114.000000,1.000000,1.000000,-2.75000,0.000000
25%,2.000000,2025-01-09 14:00:31.500000,2025-01-09 14:26:33.500000,1.000000,74.000000,74.000000,1.000000,1.100000,9.300000,0.000000,0.500000,0.000000,0.000000,NaN,1.000000,13.705000,1.000000,1.000000,0.00000,0.000000
50%,2.000000,2025-01-16 19:46:55.500000,2025-01-16 20:01:19.500000,1.000000,75.000000,140.000000,1.000000,1.740000,13.500000,0.000000,0.500000,2.070000,0.000000,NaN,1.000000,18.750000,1.000000,1.000000,0.00000,0.000000
75%,2.000000,2025-01-24 17:47:35.500000,2025-01-24 18:03:52,1.000000,97.000000,230.000000,1.000000,2.940000,19.100000,2.500000,0.500000,3.690000,0.000000,NaN,1.000000,26.465000,2.000000,1.000000,2.75000,0.000000
max,2.000000,2025-02-05 18:46:24,2025-02-05 19:11:47,99.000000,265.000000,265.000000,9.000000,84731.570000,336.200000,7.500000,4.250000,252.050000,48.760000,NaN,1.000000,371.400000,5.000000,2.000000,2.75000,0.750000
std,0.336070,NaN,NaN,1.442502,54.968061,77.251550,0.937178,990.646907,13.308342,1.348587,0.357366,3.213612,1.192984,NaN,0.130402,15.435061,0.471842,0.193092,1.27190,0.192788

In [5]:
df.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag                  str
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object